# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - v*

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows
            goexe: .exe
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    
    - name: Install
      run: go get .
    
    - name: Build
      run: > # > is used to ignore the newline
        version=$(git describe --tags --always) && 
        go build -v -o release/deploy${{ matrix.goexe }} -ldflags "-s -w 
        -X main.Version=${version} 
        -X main.Os=${{ matrix.goos }} 
        -X main.Arch=${{ matrix.goarch }}"
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    
    - name: Package
      run: cd release && tar -cvzf deploy-${{ matrix.goos }}-${{ matrix.goarch }}.tgz deploy* ../README.md
    
    - name: Deploy
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
#         tag_name: ${{ github.ref }}
#         name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
          ${{ github.event.release.body }}
        draft: false
        prerelease: false
        token: ${{ github.token }}
        files: release/deploy-${{ matrix.goos }}-${{ matrix.goarch }}.tgz