# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  label:
    types: [created]

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows
            goexe: .exe
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: 'go.sum'
    
    - name: Install
      run: go get .
    
    - name: Build
      run: go build -v -o release/deploy${{ matrix.goexe }} -ldflags "-s -w" main.go
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
    
    - name: Package
      run: cd release && tar -cvzf deploy-${{ matrix.goos }}-${{ matrix.goarch }}.tgz deploy* ../README.md
    
    - name: Deploy
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
#         tag_name: ${{ github.ref }}
#         name: Release ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
        token: ${{ github.token }}
        files: release/deploy-${{ matrix.goos }}-${{ matrix.goarch }}.tgz 
    
  script:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Write install.sh script
      if: startsWith(github.ref, 'refs/tags/')
      run: cp install.sh.d install.sh && sed -i 's/{version}/${{ github.ref }}/g' install.sh && cat install.sh
      
    - name: Deploy
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: false
        prerelease: false
        token: ${{ github.token }}
        files: install.sh
