# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - v*
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so that tags are cloned
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          # The version of Go to use.
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish binary file to npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          # 将 tag version 写入 package.json的 version 字段
          npm version ${{ github.ref }}
          npm publish

